version: '2'
services:
  jenkins:
    hostname: jenkins.local
    container_name: jenkins
    build: .
    environment:
      GITHUB_USER: "${GITHUB_USER}"
      GITHUB_PASS: "${GITHUB_PASS}"
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      # this line gives access to your local docker enironment for jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      # share initial scripts to setup jenkins
      - ./init.groovy.d:/var/jenkins_home/init.groovy.d
      # jenkins home folder
      # - ./jenkins_home:/var/jenkins_home
